### ISSUE TITLE
C# version

### ISSUE THREAD

**Issue by mapo80** [jason-li-831202/YOLO-NAS-onnxruntime#11]
Hi,

is it possible to have a C# version for .Net user?

Thanks

**Comment by jason-li-831202** [comment]
I currently have no plans to develop a C# version, but perhaps you can replace the model with a C# version provided in the repositories of yolov5/6/7. This is because the output format after converting to ONNX in the YOLO-NAS architecture of this project is the same as theirs.

**Comment by SuicunesLesson** [comment]
C# is usually already in the Visual Studio.

**Comment by mapo80** [comment]
@jason-li-831202 I've seen that the output of Yolo NAS is different from Yolo V8, so can't be used the implementation provided for yolov5/6/7.

@SuicunesLesson  C# is programming language

**Comment by jason-li-831202** [comment]
@mapo80 
The output of yolov5/6/7 is different from yolov8/9 : https://github.com/jason-li-831202/YOLO-NAS-onnxruntime/issues/9#issuecomment-1978788821

I think, you can try using the following repositories.
https://github.com/techwingslab/yolov5-net

**Comment by jason-li-831202** [comment]
Hi @mapo80, I successfully run yolo-nas onnx model in the https://github.com/techwingslab/yolov5-net repository.

And you need to rewrite the following code  :
https://github.com/techwingslab/yolov5-net/blob/7ad2924c1e0c93d7d2306784e239306943229503/src/Yolov5Net.Scorer/Models/YoloCocoP5Model.cs#L27C1-L27C24
Replace with the following line : 

    -> new[] { "outputs" },

**Comment by mapo80** [comment]
@jason-li-831202 Great info! Thanks
