### ISSUE TITLE
Can this run in Jetson Nano ? if yes please help me tutorial setting env

### ISSUE THREAD

**Issue by sonyn2741** [jason-li-831202/YOLO-NAS-onnxruntime#5]
Can this run in Jetson Nano ? if yes please help me tutorial setting env

**Comment by jason-li-831202** [comment]
I haven't run it on Jetson Nano, but on Jetson Nano, I would recommend using the TensorRT framework for inference. If you want to use ONNX Runtime on that device, maybe you can provide the current error you are encountering?

**Comment by HiepT2UH** [comment]
it seems cuda 10.2 in jetson nano is not compatible with Onnxruntime 1.10+ (GPU not available)

**Comment by jason-li-831202** [comment]
I think you can try the version 1.6.0 of Onnxruntime.
